#!/bin/bash


#BSUB -n 1
#BSUB -x
#BSUB -R "span[ptile=16]"
#BSUB -J 8_cloverLeaf
#BSUB -oo qphix_bench.out.%J
#BSUB -eo qphix_bench.err.%J
#BSUB -q cosma5
#BSUB -P dr002
#BSUB -W 00:30

export OMP_NUM_THREADS=16

export KMP_AFFINITY="granularity=fine,verbose,proclist=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],explicit"

/cosma5/data/dr002/dc-kash1/cb_8/clover_leaf
